// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protobuf/grpc_method.proto

package grpc

/*
	Params
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/golang/protobuf/ptypes/struct"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import github_com_gallactic_gallactic_crypto "github.com/gallactic/gallactic/crypto"
import github_com_gallactic_gallactic_rpc "github.com/gallactic/gallactic/rpc"
import github_com_gallactic_gallactic_core_account "github.com/gallactic/gallactic/core/account"
import github_com_gallactic_gallactic_core_validator "github.com/gallactic/gallactic/core/validator"
import github_com_gallactic_gallactic_common_binary "github.com/gallactic/gallactic/common/binary"
import github_com_tendermint_tendermint_types "github.com/tendermint/tendermint/types"
import github_com_tendermint_tendermint_p2p "github.com/tendermint/tendermint/p2p"
import github_com_tendermint_tendermint_consensus_types "github.com/tendermint/tendermint/consensus/types"
import github_com_gallactic_gallactic_core_proposal "github.com/gallactic/gallactic/core/proposal"
import github_com_gallactic_gallactic_txs "github.com/gallactic/gallactic/txs"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func (*Empty) XXX_MessageName() string {
	return "grpc.Empty"
}

type AddressParam struct {
	Address              github_com_gallactic_gallactic_crypto.Address `protobuf:"bytes,1,opt,name=Address,proto3,customtype=github.com/gallactic/gallactic/crypto.Address" json:"Address"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *AddressParam) Reset()         { *m = AddressParam{} }
func (m *AddressParam) String() string { return proto.CompactTextString(m) }
func (*AddressParam) ProtoMessage()    {}
func (*AddressParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{1}
}
func (m *AddressParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressParam.Unmarshal(m, b)
}
func (m *AddressParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressParam.Marshal(b, m, deterministic)
}
func (dst *AddressParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressParam.Merge(dst, src)
}
func (m *AddressParam) XXX_Size() int {
	return xxx_messageInfo_AddressParam.Size(m)
}
func (m *AddressParam) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressParam.DiscardUnknown(m)
}

var xxx_messageInfo_AddressParam proto.InternalMessageInfo

func (*AddressParam) XXX_MessageName() string {
	return "grpc.AddressParam"
}

type AccountParam struct {
	Account              github_com_gallactic_gallactic_rpc.FilterData `protobuf:"bytes,1,opt,name=Account,proto3,customtype=github.com/gallactic/gallactic/rpc.FilterData" json:"Account"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *AccountParam) Reset()         { *m = AccountParam{} }
func (m *AccountParam) String() string { return proto.CompactTextString(m) }
func (*AccountParam) ProtoMessage()    {}
func (*AccountParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{2}
}
func (m *AccountParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountParam.Unmarshal(m, b)
}
func (m *AccountParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountParam.Marshal(b, m, deterministic)
}
func (dst *AccountParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountParam.Merge(dst, src)
}
func (m *AccountParam) XXX_Size() int {
	return xxx_messageInfo_AccountParam.Size(m)
}
func (m *AccountParam) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountParam.DiscardUnknown(m)
}

var xxx_messageInfo_AccountParam proto.InternalMessageInfo

func (*AccountParam) XXX_MessageName() string {
	return "grpc.AccountParam"
}

type AccountsOutput struct {
	BlockHeight          uint64                                                `protobuf:"varint,1,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	Accounts             []github_com_gallactic_gallactic_core_account.Account `protobuf:"bytes,2,rep,name=Accounts,customtype=github.com/gallactic/gallactic/core/account.Account" json:"Accounts"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *AccountsOutput) Reset()         { *m = AccountsOutput{} }
func (m *AccountsOutput) String() string { return proto.CompactTextString(m) }
func (*AccountsOutput) ProtoMessage()    {}
func (*AccountsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{3}
}
func (m *AccountsOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsOutput.Unmarshal(m, b)
}
func (m *AccountsOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsOutput.Marshal(b, m, deterministic)
}
func (dst *AccountsOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsOutput.Merge(dst, src)
}
func (m *AccountsOutput) XXX_Size() int {
	return xxx_messageInfo_AccountsOutput.Size(m)
}
func (m *AccountsOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsOutput.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsOutput proto.InternalMessageInfo

func (m *AccountsOutput) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (*AccountsOutput) XXX_MessageName() string {
	return "grpc.AccountsOutput"
}

type AccountOutput struct {
	Account              github_com_gallactic_gallactic_core_account.Account `protobuf:"bytes,2,opt,name=Account,proto3,customtype=github.com/gallactic/gallactic/core/account.Account" json:"Account"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *AccountOutput) Reset()         { *m = AccountOutput{} }
func (m *AccountOutput) String() string { return proto.CompactTextString(m) }
func (*AccountOutput) ProtoMessage()    {}
func (*AccountOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{4}
}
func (m *AccountOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountOutput.Unmarshal(m, b)
}
func (m *AccountOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountOutput.Marshal(b, m, deterministic)
}
func (dst *AccountOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountOutput.Merge(dst, src)
}
func (m *AccountOutput) XXX_Size() int {
	return xxx_messageInfo_AccountOutput.Size(m)
}
func (m *AccountOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountOutput.DiscardUnknown(m)
}

var xxx_messageInfo_AccountOutput proto.InternalMessageInfo

func (*AccountOutput) XXX_MessageName() string {
	return "grpc.AccountOutput"
}

type ValidatorOutput struct {
	BlockHeight          uint64                                                    `protobuf:"varint,1,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	BondedValidators     []*github_com_gallactic_gallactic_core_validator.Validator `protobuf:"bytes,2,rep,name=BondedValidators,customtype=github.com/gallactic/gallactic/core/validator.Validator" json:"BondedValidators"`
	UnbondingValidators  []*github_com_gallactic_gallactic_core_validator.Validator `protobuf:"bytes,3,rep,name=UnbondingValidators,customtype=github.com/gallactic/gallactic/core/validator.Validator" json:"UnbondingValidators"`
	XXX_NoUnkeyedLiteral struct{}                                                  `json:"-"`
	XXX_unrecognized     []byte                                                    `json:"-"`
	XXX_sizecache        int32                                                     `json:"-"`
}

func (m *ValidatorOutput) Reset()         { *m = ValidatorOutput{} }
func (m *ValidatorOutput) String() string { return proto.CompactTextString(m) }
func (*ValidatorOutput) ProtoMessage()    {}
func (*ValidatorOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{5}
}
func (m *ValidatorOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorOutput.Unmarshal(m, b)
}
func (m *ValidatorOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorOutput.Marshal(b, m, deterministic)
}
func (dst *ValidatorOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorOutput.Merge(dst, src)
}
func (m *ValidatorOutput) XXX_Size() int {
	return xxx_messageInfo_ValidatorOutput.Size(m)
}
func (m *ValidatorOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorOutput proto.InternalMessageInfo

func (m *ValidatorOutput) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (*ValidatorOutput) XXX_MessageName() string {
	return "grpc.ValidatorOutput"
}

type StorageAtInput struct {
	Address              github_com_gallactic_gallactic_crypto.Address         `protobuf:"bytes,1,opt,name=Address,proto3,customtype=github.com/gallactic/gallactic/crypto.Address" json:"Address"`
	Key                  github_com_gallactic_gallactic_common_binary.HexBytes `protobuf:"bytes,2,opt,name=Key,proto3,customtype=github.com/gallactic/gallactic/common/binary.HexBytes" json:"Key"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *StorageAtInput) Reset()         { *m = StorageAtInput{} }
func (m *StorageAtInput) String() string { return proto.CompactTextString(m) }
func (*StorageAtInput) ProtoMessage()    {}
func (*StorageAtInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{6}
}
func (m *StorageAtInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageAtInput.Unmarshal(m, b)
}
func (m *StorageAtInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageAtInput.Marshal(b, m, deterministic)
}
func (dst *StorageAtInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageAtInput.Merge(dst, src)
}
func (m *StorageAtInput) XXX_Size() int {
	return xxx_messageInfo_StorageAtInput.Size(m)
}
func (m *StorageAtInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageAtInput.DiscardUnknown(m)
}

var xxx_messageInfo_StorageAtInput proto.InternalMessageInfo

func (*StorageAtInput) XXX_MessageName() string {
	return "grpc.StorageAtInput"
}

type StorageOutput struct {
	Key                  github_com_gallactic_gallactic_common_binary.HexBytes `protobuf:"bytes,1,opt,name=Key,proto3,customtype=github.com/gallactic/gallactic/common/binary.HexBytes" json:"Key"`
	Value                github_com_gallactic_gallactic_common_binary.HexBytes `protobuf:"bytes,2,opt,name=Value,proto3,customtype=github.com/gallactic/gallactic/common/binary.HexBytes" json:"Value"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *StorageOutput) Reset()         { *m = StorageOutput{} }
func (m *StorageOutput) String() string { return proto.CompactTextString(m) }
func (*StorageOutput) ProtoMessage()    {}
func (*StorageOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{7}
}
func (m *StorageOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageOutput.Unmarshal(m, b)
}
func (m *StorageOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageOutput.Marshal(b, m, deterministic)
}
func (dst *StorageOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageOutput.Merge(dst, src)
}
func (m *StorageOutput) XXX_Size() int {
	return xxx_messageInfo_StorageOutput.Size(m)
}
func (m *StorageOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StorageOutput proto.InternalMessageInfo

func (*StorageOutput) XXX_MessageName() string {
	return "grpc.StorageOutput"
}

type BlockInput struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockInput) Reset()         { *m = BlockInput{} }
func (m *BlockInput) String() string { return proto.CompactTextString(m) }
func (*BlockInput) ProtoMessage()    {}
func (*BlockInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{8}
}
func (m *BlockInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInput.Unmarshal(m, b)
}
func (m *BlockInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInput.Marshal(b, m, deterministic)
}
func (dst *BlockInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInput.Merge(dst, src)
}
func (m *BlockInput) XXX_Size() int {
	return xxx_messageInfo_BlockInput.Size(m)
}
func (m *BlockInput) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInput.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInput proto.InternalMessageInfo

func (m *BlockInput) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (*BlockInput) XXX_MessageName() string {
	return "grpc.BlockInput"
}

type BlocksInput struct {
	MinHeight            uint64   `protobuf:"varint,1,opt,name=minHeight,proto3" json:"minHeight,omitempty"`
	MaxHeight            uint64   `protobuf:"varint,2,opt,name=maxHeight,proto3" json:"maxHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlocksInput) Reset()         { *m = BlocksInput{} }
func (m *BlocksInput) String() string { return proto.CompactTextString(m) }
func (*BlocksInput) ProtoMessage()    {}
func (*BlocksInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{9}
}
func (m *BlocksInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksInput.Unmarshal(m, b)
}
func (m *BlocksInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksInput.Marshal(b, m, deterministic)
}
func (dst *BlocksInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksInput.Merge(dst, src)
}
func (m *BlocksInput) XXX_Size() int {
	return xxx_messageInfo_BlocksInput.Size(m)
}
func (m *BlocksInput) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksInput.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksInput proto.InternalMessageInfo

func (m *BlocksInput) GetMinHeight() uint64 {
	if m != nil {
		return m.MinHeight
	}
	return 0
}

func (m *BlocksInput) GetMaxHeight() uint64 {
	if m != nil {
		return m.MaxHeight
	}
	return 0
}

func (*BlocksInput) XXX_MessageName() string {
	return "grpc.BlocksInput"
}

type BlockOutput struct {
	BlockMeta            *github_com_tendermint_tendermint_types.BlockMeta `protobuf:"bytes,1,rep,name=BlockMeta,customtype=github.com/tendermint/tendermint/types.BlockMeta" json:"BlockMeta"`
	Block                *github_com_tendermint_tendermint_types.Block     `protobuf:"bytes,2,rep,name=Block,customtype=github.com/tendermint/tendermint/types.Block" json:"Block"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *BlockOutput) Reset()         { *m = BlockOutput{} }
func (m *BlockOutput) String() string { return proto.CompactTextString(m) }
func (*BlockOutput) ProtoMessage()    {}
func (*BlockOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{10}
}
func (m *BlockOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockOutput.Unmarshal(m, b)
}
func (m *BlockOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockOutput.Marshal(b, m, deterministic)
}
func (dst *BlockOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockOutput.Merge(dst, src)
}
func (m *BlockOutput) XXX_Size() int {
	return xxx_messageInfo_BlockOutput.Size(m)
}
func (m *BlockOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockOutput.DiscardUnknown(m)
}

var xxx_messageInfo_BlockOutput proto.InternalMessageInfo

func (*BlockOutput) XXX_MessageName() string {
	return "grpc.BlockOutput"
}

type BlocksOutput struct {
	LastHeight           int                                            `protobuf:"varint,1,opt,name=LastHeight,proto3" json:"LastHeight,omitempty"`
	BlockMeta            []*github_com_tendermint_tendermint_types.BlockMeta `protobuf:"bytes,2,rep,name=BlockMeta,customtype=github.com/tendermint/tendermint/types.BlockMeta" json:"BlockMeta"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *BlocksOutput) Reset()         { *m = BlocksOutput{} }
func (m *BlocksOutput) String() string { return proto.CompactTextString(m) }
func (*BlocksOutput) ProtoMessage()    {}
func (*BlocksOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{11}
}
func (m *BlocksOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksOutput.Unmarshal(m, b)
}
func (m *BlocksOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksOutput.Marshal(b, m, deterministic)
}
func (dst *BlocksOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksOutput.Merge(dst, src)
}
func (m *BlocksOutput) XXX_Size() int {
	return xxx_messageInfo_BlocksOutput.Size(m)
}
func (m *BlocksOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksOutput.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksOutput proto.InternalMessageInfo

func (m *BlocksOutput) GetLastHeight() int {
	if m != nil {
		return m.LastHeight
	}
	return 0
}

func (*BlocksOutput) XXX_MessageName() string {
	return "grpc.BlocksOutput"
}

type StatusOutput struct {
	NodeInfo             github_com_tendermint_tendermint_p2p.NodeInfo         `protobuf:"bytes,1,opt,name=NodeInfo,proto3,customtype=github.com/tendermint/tendermint/p2p.NodeInfo" json:"NodeInfo"`
	GenesisHash          github_com_gallactic_gallactic_common_binary.HexBytes `protobuf:"bytes,2,opt,name=GenesisHash,proto3,customtype=github.com/gallactic/gallactic/common/binary.HexBytes" json:"GenesisHash"`
	PubKey               github_com_gallactic_gallactic_crypto.PublicKey       `protobuf:"bytes,3,opt,name=PubKey,proto3,customtype=github.com/gallactic/gallactic/crypto.PublicKey" json:"PubKey"`
	LatestBlockHash      github_com_gallactic_gallactic_common_binary.HexBytes `protobuf:"bytes,4,opt,name=LatestBlockHash,proto3,customtype=github.com/gallactic/gallactic/common/binary.HexBytes" json:"LatestBlockHash"`
	LatestBlockHeight    uint64                                                `protobuf:"varint,5,opt,name=LatestBlockHeight,proto3" json:"LatestBlockHeight,omitempty"`
	LatestBlockTime      int64                                                 `protobuf:"varint,6,opt,name=LatestBlockTime,proto3" json:"LatestBlockTime,omitempty"`
	NodeVersion          string                                                `protobuf:"bytes,7,opt,name=NodeVersion,proto3" json:"NodeVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *StatusOutput) Reset()         { *m = StatusOutput{} }
func (m *StatusOutput) String() string { return proto.CompactTextString(m) }
func (*StatusOutput) ProtoMessage()    {}
func (*StatusOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{12}
}
func (m *StatusOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusOutput.Unmarshal(m, b)
}
func (m *StatusOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusOutput.Marshal(b, m, deterministic)
}
func (dst *StatusOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusOutput.Merge(dst, src)
}
func (m *StatusOutput) XXX_Size() int {
	return xxx_messageInfo_StatusOutput.Size(m)
}
func (m *StatusOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StatusOutput proto.InternalMessageInfo

func (m *StatusOutput) GetLatestBlockHeight() uint64 {
	if m != nil {
		return m.LatestBlockHeight
	}
	return 0
}

func (m *StatusOutput) GetLatestBlockTime() int64 {
	if m != nil {
		return m.LatestBlockTime
	}
	return 0
}

func (m *StatusOutput) GetNodeVersion() string {
	if m != nil {
		return m.NodeVersion
	}
	return ""
}

func (*StatusOutput) XXX_MessageName() string {
	return "grpc.StatusOutput"
}

type DumpConsensusStateOutput struct {
	RoundState           github_com_tendermint_tendermint_consensus_types.RoundStateSimple `protobuf:"bytes,1,opt,name=RoundState,proto3,customtype=github.com/tendermint/tendermint/consensus/types.RoundStateSimple" json:"RoundState"`
	PeerRoundStates      []*github_com_tendermint_tendermint_consensus_types.PeerRoundState `protobuf:"bytes,2,rep,name=PeerRoundStates,customtype=github.com/tendermint/tendermint/consensus/types.PeerRoundState" json:"PeerRoundStates"`
	XXX_NoUnkeyedLiteral struct{}                                                          `json:"-"`
	XXX_unrecognized     []byte                                                            `json:"-"`
	XXX_sizecache        int32                                                             `json:"-"`
}

func (m *DumpConsensusStateOutput) Reset()         { *m = DumpConsensusStateOutput{} }
func (m *DumpConsensusStateOutput) String() string { return proto.CompactTextString(m) }
func (*DumpConsensusStateOutput) ProtoMessage()    {}
func (*DumpConsensusStateOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{13}
}
func (m *DumpConsensusStateOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpConsensusStateOutput.Unmarshal(m, b)
}
func (m *DumpConsensusStateOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpConsensusStateOutput.Marshal(b, m, deterministic)
}
func (dst *DumpConsensusStateOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpConsensusStateOutput.Merge(dst, src)
}
func (m *DumpConsensusStateOutput) XXX_Size() int {
	return xxx_messageInfo_DumpConsensusStateOutput.Size(m)
}
func (m *DumpConsensusStateOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpConsensusStateOutput.DiscardUnknown(m)
}

var xxx_messageInfo_DumpConsensusStateOutput proto.InternalMessageInfo

func (*DumpConsensusStateOutput) XXX_MessageName() string {
	return "grpc.DumpConsensusStateOutput"
}

type GenesisOutput struct {
	Genesis              *github_com_gallactic_gallactic_core_proposal.Genesis `protobuf:"bytes,1,rep,name=Genesis,customtype=github.com/gallactic/gallactic/core/proposal.Genesis" json:"Genesis"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *GenesisOutput) Reset()         { *m = GenesisOutput{} }
func (m *GenesisOutput) String() string { return proto.CompactTextString(m) }
func (*GenesisOutput) ProtoMessage()    {}
func (*GenesisOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{14}
}
func (m *GenesisOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisOutput.Unmarshal(m, b)
}
func (m *GenesisOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisOutput.Marshal(b, m, deterministic)
}
func (dst *GenesisOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisOutput.Merge(dst, src)
}
func (m *GenesisOutput) XXX_Size() int {
	return xxx_messageInfo_GenesisOutput.Size(m)
}
func (m *GenesisOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisOutput proto.InternalMessageInfo

func (*GenesisOutput) XXX_MessageName() string {
	return "grpc.GenesisOutput"
}

type ChainIdOutput struct {
	ChainName            string                                                `protobuf:"bytes,1,opt,name=ChainName,proto3" json:"ChainName,omitempty"`
	ChainId              string                                                `protobuf:"bytes,2,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	GenesisHash          github_com_gallactic_gallactic_common_binary.HexBytes `protobuf:"bytes,3,opt,name=GenesisHash,proto3,customtype=github.com/gallactic/gallactic/common/binary.HexBytes" json:"GenesisHash"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *ChainIdOutput) Reset()         { *m = ChainIdOutput{} }
func (m *ChainIdOutput) String() string { return proto.CompactTextString(m) }
func (*ChainIdOutput) ProtoMessage()    {}
func (*ChainIdOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{15}
}
func (m *ChainIdOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainIdOutput.Unmarshal(m, b)
}
func (m *ChainIdOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainIdOutput.Marshal(b, m, deterministic)
}
func (dst *ChainIdOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainIdOutput.Merge(dst, src)
}
func (m *ChainIdOutput) XXX_Size() int {
	return xxx_messageInfo_ChainIdOutput.Size(m)
}
func (m *ChainIdOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainIdOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ChainIdOutput proto.InternalMessageInfo

func (m *ChainIdOutput) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *ChainIdOutput) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (*ChainIdOutput) XXX_MessageName() string {
	return "grpc.ChainIdOutput"
}

type UnconfirmedTxsOutput struct {
	Count                int32                                         `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Txs                  []*github_com_gallactic_gallactic_txs.Envelope `protobuf:"bytes,3,rep,name=Txs,customtype=github.com/gallactic/gallactic/txs.Envelope" json:"Txs"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *UnconfirmedTxsOutput) Reset()         { *m = UnconfirmedTxsOutput{} }
func (m *UnconfirmedTxsOutput) String() string { return proto.CompactTextString(m) }
func (*UnconfirmedTxsOutput) ProtoMessage()    {}
func (*UnconfirmedTxsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{16}
}
func (m *UnconfirmedTxsOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnconfirmedTxsOutput.Unmarshal(m, b)
}
func (m *UnconfirmedTxsOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnconfirmedTxsOutput.Marshal(b, m, deterministic)
}
func (dst *UnconfirmedTxsOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnconfirmedTxsOutput.Merge(dst, src)
}
func (m *UnconfirmedTxsOutput) XXX_Size() int {
	return xxx_messageInfo_UnconfirmedTxsOutput.Size(m)
}
func (m *UnconfirmedTxsOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_UnconfirmedTxsOutput.DiscardUnknown(m)
}

var xxx_messageInfo_UnconfirmedTxsOutput proto.InternalMessageInfo

func (m *UnconfirmedTxsOutput) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (*UnconfirmedTxsOutput) XXX_MessageName() string {
	return "grpc.UnconfirmedTxsOutput"
}

type UnconfirmedTxsInput struct {
	MaxTxs               int32    `protobuf:"varint,1,opt,name=maxTxs,proto3" json:"maxTxs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnconfirmedTxsInput) Reset()         { *m = UnconfirmedTxsInput{} }
func (m *UnconfirmedTxsInput) String() string { return proto.CompactTextString(m) }
func (*UnconfirmedTxsInput) ProtoMessage()    {}
func (*UnconfirmedTxsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{17}
}
func (m *UnconfirmedTxsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnconfirmedTxsInput.Unmarshal(m, b)
}
func (m *UnconfirmedTxsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnconfirmedTxsInput.Marshal(b, m, deterministic)
}
func (dst *UnconfirmedTxsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnconfirmedTxsInput.Merge(dst, src)
}
func (m *UnconfirmedTxsInput) XXX_Size() int {
	return xxx_messageInfo_UnconfirmedTxsInput.Size(m)
}
func (m *UnconfirmedTxsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UnconfirmedTxsInput.DiscardUnknown(m)
}

var xxx_messageInfo_UnconfirmedTxsInput proto.InternalMessageInfo

func (m *UnconfirmedTxsInput) GetMaxTxs() int32 {
	if m != nil {
		return m.MaxTxs
	}
	return 0
}

func (*UnconfirmedTxsInput) XXX_MessageName() string {
	return "grpc.UnconfirmedTxsInput"
}

type BlockTxsOutput struct {
	Count                int32                                         `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Txs                  []github_com_gallactic_gallactic_txs.Envelope `protobuf:"bytes,3,rep,name=Txs,customtype=github.com/gallactic/gallactic/txs.Envelope" json:"Txs"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *BlockTxsOutput) Reset()         { *m = BlockTxsOutput{} }
func (m *BlockTxsOutput) String() string { return proto.CompactTextString(m) }
func (*BlockTxsOutput) ProtoMessage()    {}
func (*BlockTxsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{18}
}
func (m *BlockTxsOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockTxsOutput.Unmarshal(m, b)
}
func (m *BlockTxsOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockTxsOutput.Marshal(b, m, deterministic)
}
func (dst *BlockTxsOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockTxsOutput.Merge(dst, src)
}
func (m *BlockTxsOutput) XXX_Size() int {
	return xxx_messageInfo_BlockTxsOutput.Size(m)
}
func (m *BlockTxsOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockTxsOutput.DiscardUnknown(m)
}

var xxx_messageInfo_BlockTxsOutput proto.InternalMessageInfo

func (m *BlockTxsOutput) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (*BlockTxsOutput) XXX_MessageName() string {
	return "grpc.BlockTxsOutput"
}

type NetInfoOutput struct {
	Listening            bool                                      `protobuf:"varint,1,opt,name=Listening,proto3" json:"Listening,omitempty"`
	Listeners            []string                                  `protobuf:"bytes,2,rep,name=Listeners" json:"Listeners,omitempty"`
	Peer                 []*github_com_gallactic_gallactic_rpc.Peer `protobuf:"bytes,3,rep,name=Peer,customtype=github.com/gallactic/gallactic/rpc.Peer" json:"Peer"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *NetInfoOutput) Reset()         { *m = NetInfoOutput{} }
func (m *NetInfoOutput) String() string { return proto.CompactTextString(m) }
func (*NetInfoOutput) ProtoMessage()    {}
func (*NetInfoOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{19}
}
func (m *NetInfoOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoOutput.Unmarshal(m, b)
}
func (m *NetInfoOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoOutput.Marshal(b, m, deterministic)
}
func (dst *NetInfoOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoOutput.Merge(dst, src)
}
func (m *NetInfoOutput) XXX_Size() int {
	return xxx_messageInfo_NetInfoOutput.Size(m)
}
func (m *NetInfoOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoOutput.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoOutput proto.InternalMessageInfo

func (m *NetInfoOutput) GetListening() bool {
	if m != nil {
		return m.Listening
	}
	return false
}

func (m *NetInfoOutput) GetListeners() []string {
	if m != nil {
		return m.Listeners
	}
	return nil
}

func (*NetInfoOutput) XXX_MessageName() string {
	return "grpc.NetInfoOutput"
}

type PeersOutput struct {
	Peer                 []*github_com_gallactic_gallactic_rpc.Peer `protobuf:"bytes,1,rep,name=Peer,customtype=github.com/gallactic/gallactic/rpc.Peer" json:"Peer"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *PeersOutput) Reset()         { *m = PeersOutput{} }
func (m *PeersOutput) String() string { return proto.CompactTextString(m) }
func (*PeersOutput) ProtoMessage()    {}
func (*PeersOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{20}
}
func (m *PeersOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersOutput.Unmarshal(m, b)
}
func (m *PeersOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersOutput.Marshal(b, m, deterministic)
}
func (dst *PeersOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersOutput.Merge(dst, src)
}
func (m *PeersOutput) XXX_Size() int {
	return xxx_messageInfo_PeersOutput.Size(m)
}
func (m *PeersOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersOutput.DiscardUnknown(m)
}

var xxx_messageInfo_PeersOutput proto.InternalMessageInfo

func (*PeersOutput) XXX_MessageName() string {
	return "grpc.PeersOutput"
}

type Transactparam struct {
	Txs                  []github_com_gallactic_gallactic_txs.Envelope `protobuf:"bytes,1,rep,name=txs,customtype=github.com/gallactic/gallactic/txs.Envelope" json:"txs"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *Transactparam) Reset()         { *m = Transactparam{} }
func (m *Transactparam) String() string { return proto.CompactTextString(m) }
func (*Transactparam) ProtoMessage()    {}
func (*Transactparam) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{21}
}
func (m *Transactparam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactparam.Unmarshal(m, b)
}
func (m *Transactparam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactparam.Marshal(b, m, deterministic)
}
func (dst *Transactparam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactparam.Merge(dst, src)
}
func (m *Transactparam) XXX_Size() int {
	return xxx_messageInfo_Transactparam.Size(m)
}
func (m *Transactparam) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactparam.DiscardUnknown(m)
}

var xxx_messageInfo_Transactparam proto.InternalMessageInfo

func (*Transactparam) XXX_MessageName() string {
	return "grpc.Transactparam"
}

type Receipt struct {
	TxHash               []github_com_gallactic_gallactic_txs.Receipt `protobuf:"bytes,1,rep,name=TxHash,customtype=github.com/gallactic/gallactic/txs.Receipt" json:"TxHash"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_method_421c6d7e4a667b54, []int{22}
}
func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (dst *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(dst, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (*Receipt) XXX_MessageName() string {
	return "grpc.Receipt"
}
func init() {
	proto.RegisterType((*Empty)(nil), "grpc.Empty")
	proto.RegisterType((*AddressParam)(nil), "grpc.AddressParam")
	proto.RegisterType((*AccountParam)(nil), "grpc.AccountParam")
	proto.RegisterType((*AccountsOutput)(nil), "grpc.AccountsOutput")
	proto.RegisterType((*AccountOutput)(nil), "grpc.AccountOutput")
	proto.RegisterType((*ValidatorOutput)(nil), "grpc.ValidatorOutput")
	proto.RegisterType((*StorageAtInput)(nil), "grpc.StorageAtInput")
	proto.RegisterType((*StorageOutput)(nil), "grpc.StorageOutput")
	proto.RegisterType((*BlockInput)(nil), "grpc.BlockInput")
	proto.RegisterType((*BlocksInput)(nil), "grpc.BlocksInput")
	proto.RegisterType((*BlockOutput)(nil), "grpc.BlockOutput")
	proto.RegisterType((*BlocksOutput)(nil), "grpc.BlocksOutput")
	proto.RegisterType((*StatusOutput)(nil), "grpc.StatusOutput")
	proto.RegisterType((*DumpConsensusStateOutput)(nil), "grpc.DumpConsensusStateOutput")
	proto.RegisterType((*GenesisOutput)(nil), "grpc.GenesisOutput")
	proto.RegisterType((*ChainIdOutput)(nil), "grpc.ChainIdOutput")
	proto.RegisterType((*UnconfirmedTxsOutput)(nil), "grpc.UnconfirmedTxsOutput")
	proto.RegisterType((*UnconfirmedTxsInput)(nil), "grpc.UnconfirmedTxsInput")
	proto.RegisterType((*BlockTxsOutput)(nil), "grpc.BlockTxsOutput")
	proto.RegisterType((*NetInfoOutput)(nil), "grpc.NetInfoOutput")
	proto.RegisterType((*PeersOutput)(nil), "grpc.PeersOutput")
	proto.RegisterType((*Transactparam)(nil), "grpc.Transactparam")
	proto.RegisterType((*Receipt)(nil), "grpc.Receipt")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	GetAccount(ctx context.Context, in *AddressParam, opts ...grpc.CallOption) (*AccountOutput, error)
	GetAccounts(ctx context.Context, in *AccountParam, opts ...grpc.CallOption) (*AccountsOutput, error)
	GetValidators(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ValidatorOutput, error)
	GetStorage(ctx context.Context, in *StorageAtInput, opts ...grpc.CallOption) (*StorageOutput, error)
	GetStorageAt(ctx context.Context, in *StorageAtInput, opts ...grpc.CallOption) (*StorageOutput, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) GetAccount(ctx context.Context, in *AddressParam, opts ...grpc.CallOption) (*AccountOutput, error) {
	out := new(AccountOutput)
	err := c.cc.Invoke(ctx, "/grpc.Accounts/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetAccounts(ctx context.Context, in *AccountParam, opts ...grpc.CallOption) (*AccountsOutput, error) {
	out := new(AccountsOutput)
	err := c.cc.Invoke(ctx, "/grpc.Accounts/GetAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetValidators(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ValidatorOutput, error) {
	out := new(ValidatorOutput)
	err := c.cc.Invoke(ctx, "/grpc.Accounts/GetValidators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetStorage(ctx context.Context, in *StorageAtInput, opts ...grpc.CallOption) (*StorageOutput, error) {
	out := new(StorageOutput)
	err := c.cc.Invoke(ctx, "/grpc.Accounts/GetStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetStorageAt(ctx context.Context, in *StorageAtInput, opts ...grpc.CallOption) (*StorageOutput, error) {
	out := new(StorageOutput)
	err := c.cc.Invoke(ctx, "/grpc.Accounts/GetStorageAt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	GetAccount(context.Context, *AddressParam) (*AccountOutput, error)
	GetAccounts(context.Context, *AccountParam) (*AccountsOutput, error)
	GetValidators(context.Context, *Empty) (*ValidatorOutput, error)
	GetStorage(context.Context, *StorageAtInput) (*StorageOutput, error)
	GetStorageAt(context.Context, *StorageAtInput) (*StorageOutput, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Accounts/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAccount(ctx, req.(*AddressParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Accounts/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAccounts(ctx, req.(*AccountParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Accounts/GetValidators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetValidators(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageAtInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Accounts/GetStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetStorage(ctx, req.(*StorageAtInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetStorageAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageAtInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetStorageAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Accounts/GetStorageAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetStorageAt(ctx, req.(*StorageAtInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _Accounts_GetAccount_Handler,
		},
		{
			MethodName: "GetAccounts",
			Handler:    _Accounts_GetAccounts_Handler,
		},
		{
			MethodName: "GetValidators",
			Handler:    _Accounts_GetValidators_Handler,
		},
		{
			MethodName: "GetStorage",
			Handler:    _Accounts_GetStorage_Handler,
		},
		{
			MethodName: "GetStorageAt",
			Handler:    _Accounts_GetStorageAt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/grpc_method.proto",
}

// BlockChainClient is the client API for BlockChain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockChainClient interface {
	GetBlock(ctx context.Context, in *BlockInput, opts ...grpc.CallOption) (*BlockOutput, error)
	GetBlocks(ctx context.Context, in *BlocksInput, opts ...grpc.CallOption) (*BlocksOutput, error)
	Getstatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusOutput, error)
	GetLatestBlock(ctx context.Context, in *BlockInput, opts ...grpc.CallOption) (*BlockOutput, error)
	GetConsensusState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DumpConsensusStateOutput, error)
	GetGenesis(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenesisOutput, error)
	GetChainID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChainIdOutput, error)
	GetBlockTxs(ctx context.Context, in *BlockInput, opts ...grpc.CallOption) (*BlockTxsOutput, error)
}

type blockChainClient struct {
	cc *grpc.ClientConn
}

func NewBlockChainClient(cc *grpc.ClientConn) BlockChainClient {
	return &blockChainClient{cc}
}

func (c *blockChainClient) GetBlock(ctx context.Context, in *BlockInput, opts ...grpc.CallOption) (*BlockOutput, error) {
	out := new(BlockOutput)
	err := c.cc.Invoke(ctx, "/grpc.BlockChain/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockChainClient) GetBlocks(ctx context.Context, in *BlocksInput, opts ...grpc.CallOption) (*BlocksOutput, error) {
	out := new(BlocksOutput)
	err := c.cc.Invoke(ctx, "/grpc.BlockChain/GetBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockChainClient) Getstatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusOutput, error) {
	out := new(StatusOutput)
	err := c.cc.Invoke(ctx, "/grpc.BlockChain/Getstatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockChainClient) GetLatestBlock(ctx context.Context, in *BlockInput, opts ...grpc.CallOption) (*BlockOutput, error) {
	out := new(BlockOutput)
	err := c.cc.Invoke(ctx, "/grpc.BlockChain/GetLatestBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockChainClient) GetConsensusState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DumpConsensusStateOutput, error) {
	out := new(DumpConsensusStateOutput)
	err := c.cc.Invoke(ctx, "/grpc.BlockChain/GetConsensusState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockChainClient) GetGenesis(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenesisOutput, error) {
	out := new(GenesisOutput)
	err := c.cc.Invoke(ctx, "/grpc.BlockChain/GetGenesis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockChainClient) GetChainID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChainIdOutput, error) {
	out := new(ChainIdOutput)
	err := c.cc.Invoke(ctx, "/grpc.BlockChain/GetChainID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockChainClient) GetBlockTxs(ctx context.Context, in *BlockInput, opts ...grpc.CallOption) (*BlockTxsOutput, error) {
	out := new(BlockTxsOutput)
	err := c.cc.Invoke(ctx, "/grpc.BlockChain/GetBlockTxs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockChainServer is the server API for BlockChain service.
type BlockChainServer interface {
	GetBlock(context.Context, *BlockInput) (*BlockOutput, error)
	GetBlocks(context.Context, *BlocksInput) (*BlocksOutput, error)
	Getstatus(context.Context, *Empty) (*StatusOutput, error)
	GetLatestBlock(context.Context, *BlockInput) (*BlockOutput, error)
	GetConsensusState(context.Context, *Empty) (*DumpConsensusStateOutput, error)
	GetGenesis(context.Context, *Empty) (*GenesisOutput, error)
	GetChainID(context.Context, *Empty) (*ChainIdOutput, error)
	GetBlockTxs(context.Context, *BlockInput) (*BlockTxsOutput, error)
}

func RegisterBlockChainServer(s *grpc.Server, srv BlockChainServer) {
	s.RegisterService(&_BlockChain_serviceDesc, srv)
}

func _BlockChain_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BlockChain/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetBlock(ctx, req.(*BlockInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockChain_GetBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlocksInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BlockChain/GetBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetBlocks(ctx, req.(*BlocksInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockChain_Getstatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).Getstatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BlockChain/Getstatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).Getstatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockChain_GetLatestBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetLatestBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BlockChain/GetLatestBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetLatestBlock(ctx, req.(*BlockInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockChain_GetConsensusState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetConsensusState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BlockChain/GetConsensusState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetConsensusState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockChain_GetGenesis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetGenesis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BlockChain/GetGenesis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetGenesis(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockChain_GetChainID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetChainID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BlockChain/GetChainID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetChainID(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockChain_GetBlockTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetBlockTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BlockChain/GetBlockTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetBlockTxs(ctx, req.(*BlockInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockChain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.BlockChain",
	HandlerType: (*BlockChainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlock",
			Handler:    _BlockChain_GetBlock_Handler,
		},
		{
			MethodName: "GetBlocks",
			Handler:    _BlockChain_GetBlocks_Handler,
		},
		{
			MethodName: "Getstatus",
			Handler:    _BlockChain_Getstatus_Handler,
		},
		{
			MethodName: "GetLatestBlock",
			Handler:    _BlockChain_GetLatestBlock_Handler,
		},
		{
			MethodName: "GetConsensusState",
			Handler:    _BlockChain_GetConsensusState_Handler,
		},
		{
			MethodName: "GetGenesis",
			Handler:    _BlockChain_GetGenesis_Handler,
		},
		{
			MethodName: "GetChainID",
			Handler:    _BlockChain_GetChainID_Handler,
		},
		{
			MethodName: "GetBlockTxs",
			Handler:    _BlockChain_GetBlockTxs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/grpc_method.proto",
}

// TransactionClient is the client API for Transaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionClient interface {
	BroadcastTx(ctx context.Context, in *Transactparam, opts ...grpc.CallOption) (*Receipt, error)
	GetUnconfirmedTxs(ctx context.Context, in *UnconfirmedTxsInput, opts ...grpc.CallOption) (*UnconfirmedTxsOutput, error)
}

type transactionClient struct {
	cc *grpc.ClientConn
}

func NewTransactionClient(cc *grpc.ClientConn) TransactionClient {
	return &transactionClient{cc}
}

func (c *transactionClient) BroadcastTx(ctx context.Context, in *Transactparam, opts ...grpc.CallOption) (*Receipt, error) {
	out := new(Receipt)
	err := c.cc.Invoke(ctx, "/grpc.Transaction/BroadcastTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetUnconfirmedTxs(ctx context.Context, in *UnconfirmedTxsInput, opts ...grpc.CallOption) (*UnconfirmedTxsOutput, error) {
	out := new(UnconfirmedTxsOutput)
	err := c.cc.Invoke(ctx, "/grpc.Transaction/GetUnconfirmedTxs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServer is the server API for Transaction service.
type TransactionServer interface {
	BroadcastTx(context.Context, *Transactparam) (*Receipt, error)
	GetUnconfirmedTxs(context.Context, *UnconfirmedTxsInput) (*UnconfirmedTxsOutput, error)
}

func RegisterTransactionServer(s *grpc.Server, srv TransactionServer) {
	s.RegisterService(&_Transaction_serviceDesc, srv)
}

func _Transaction_BroadcastTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transactparam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).BroadcastTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Transaction/BroadcastTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).BroadcastTx(ctx, req.(*Transactparam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetUnconfirmedTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnconfirmedTxsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetUnconfirmedTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Transaction/GetUnconfirmedTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetUnconfirmedTxs(ctx, req.(*UnconfirmedTxsInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Transaction",
	HandlerType: (*TransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastTx",
			Handler:    _Transaction_BroadcastTx_Handler,
		},
		{
			MethodName: "GetUnconfirmedTxs",
			Handler:    _Transaction_GetUnconfirmedTxs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/grpc_method.proto",
}

// NetworkClient is the client API for Network service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkClient interface {
	GetNetworkInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetInfoOutput, error)
	GetPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeersOutput, error)
}

type networkClient struct {
	cc *grpc.ClientConn
}

func NewNetworkClient(cc *grpc.ClientConn) NetworkClient {
	return &networkClient{cc}
}

func (c *networkClient) GetNetworkInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetInfoOutput, error) {
	out := new(NetInfoOutput)
	err := c.cc.Invoke(ctx, "/grpc.Network/GetNetworkInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) GetPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeersOutput, error) {
	out := new(PeersOutput)
	err := c.cc.Invoke(ctx, "/grpc.Network/GetPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServer is the server API for Network service.
type NetworkServer interface {
	GetNetworkInfo(context.Context, *Empty) (*NetInfoOutput, error)
	GetPeers(context.Context, *Empty) (*PeersOutput, error)
}

func RegisterNetworkServer(s *grpc.Server, srv NetworkServer) {
	s.RegisterService(&_Network_serviceDesc, srv)
}

func _Network_GetNetworkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).GetNetworkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Network/GetNetworkInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).GetNetworkInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Network/GetPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).GetPeers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Network_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Network",
	HandlerType: (*NetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNetworkInfo",
			Handler:    _Network_GetNetworkInfo_Handler,
		},
		{
			MethodName: "GetPeers",
			Handler:    _Network_GetPeers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/grpc_method.proto",
}

func init() {
	proto.RegisterFile("protobuf/grpc_method.proto", fileDescriptor_grpc_method_421c6d7e4a667b54)
}

var fileDescriptor_grpc_method_421c6d7e4a667b54 = []byte{
	// 1404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0xc6, 0xf9, 0xe5, 0x67, 0x3b, 0x6d, 0xa7, 0x01, 0x19, 0x2b, 0x72, 0xa3, 0x15, 0x12,
	0x51, 0x69, 0xd7, 0xe0, 0x34, 0x0a, 0x08, 0x50, 0x89, 0xdb, 0x92, 0xa6, 0x2d, 0x49, 0xd8, 0xa4,
	0xb9, 0x46, 0xe3, 0xf5, 0xc4, 0x59, 0xd5, 0x3b, 0xb3, 0xec, 0x8e, 0x8b, 0x7d, 0xe6, 0x80, 0x90,
	0x40, 0x9c, 0x90, 0x38, 0x22, 0x38, 0xc0, 0x01, 0x09, 0x81, 0xc4, 0x9d, 0x63, 0x2f, 0x48, 0x9c,
	0x39, 0x54, 0xa8, 0xf9, 0x1f, 0x38, 0xa3, 0x9d, 0x79, 0xeb, 0xdd, 0x4d, 0x4d, 0xe3, 0x80, 0x2b,
	0x4e, 0xf6, 0x7b, 0x33, 0xef, 0x7b, 0xdf, 0xbc, 0x7d, 0xef, 0xcd, 0x1b, 0xa8, 0xf8, 0x81, 0x90,
	0xa2, 0xd9, 0x3d, 0xac, 0xb5, 0x03, 0xdf, 0x39, 0xf0, 0x98, 0x3c, 0x12, 0x2d, 0x4b, 0x29, 0xc9,
	0x54, 0xa4, 0xaa, 0x5c, 0x6d, 0xbb, 0xf2, 0xa8, 0xdb, 0xb4, 0x1c, 0xe1, 0xd5, 0xda, 0xa2, 0x2d,
	0x6a, 0x89, 0x85, 0x68, 0x0b, 0x25, 0xa8, 0x7f, 0xda, 0xa8, 0xb2, 0xd8, 0x16, 0xa2, 0xdd, 0x61,
	0x35, 0xea, 0xbb, 0x35, 0xca, 0xb9, 0x90, 0x54, 0xba, 0x82, 0x87, 0x27, 0x56, 0x07, 0x18, 0xa1,
	0x0c, 0xba, 0x8e, 0xd4, 0xab, 0xe6, 0x2c, 0x4c, 0xdf, 0xf2, 0x7c, 0xd9, 0x37, 0x0f, 0xa0, 0xb8,
	0xde, 0x6a, 0x05, 0x2c, 0x0c, 0x77, 0x68, 0x40, 0x3d, 0xb2, 0x0d, 0xb3, 0x28, 0x97, 0x8d, 0x25,
	0x63, 0xb9, 0xd8, 0x58, 0x7d, 0xf4, 0xf8, 0xd2, 0xc4, 0x1f, 0x8f, 0x2f, 0x65, 0xc8, 0xd1, 0x4e,
	0x87, 0x3a, 0xd2, 0x75, 0x52, 0xff, 0x9c, 0xa0, 0xef, 0x4b, 0x61, 0xa1, 0xb1, 0x1d, 0xa3, 0x28,
	0x07, 0x8e, 0x23, 0xba, 0x5c, 0x26, 0x0e, 0xb4, 0x7c, 0x46, 0x07, 0x81, 0xef, 0x58, 0xef, 0xb9,
	0x1d, 0xc9, 0x82, 0x9b, 0x54, 0x52, 0x3b, 0x46, 0x31, 0xbf, 0x33, 0x60, 0x1e, 0xff, 0x87, 0xdb,
	0x5d, 0xe9, 0x77, 0x25, 0x59, 0x82, 0x42, 0xa3, 0x23, 0x9c, 0x07, 0xb7, 0x99, 0xdb, 0x3e, 0xd2,
	0x7e, 0xa6, 0xec, 0xb4, 0x8a, 0x84, 0x30, 0x17, 0xdb, 0x94, 0x27, 0x97, 0x72, 0xcb, 0x85, 0x7a,
	0xc5, 0xd2, 0x01, 0xb3, 0xe2, 0x80, 0x59, 0xf7, 0xdc, 0x50, 0xee, 0xd3, 0x4e, 0x97, 0x35, 0xde,
	0x42, 0x8a, 0x2b, 0xa7, 0xc5, 0x40, 0x04, 0xac, 0x46, 0x35, 0xae, 0x85, 0xf8, 0xf6, 0xc0, 0x91,
	0x79, 0x08, 0x25, 0xfc, 0x8f, 0x3c, 0xef, 0x27, 0xb1, 0x98, 0x54, 0xb1, 0xf8, 0x4f, 0x8e, 0x06,
	0x11, 0xf9, 0x6d, 0x12, 0xce, 0xed, 0xd3, 0x8e, 0xdb, 0xa2, 0x52, 0x04, 0x23, 0x87, 0xe4, 0x13,
	0x03, 0xce, 0x37, 0x04, 0x6f, 0xb1, 0xd6, 0xc0, 0x76, 0x94, 0xd8, 0x5c, 0x47, 0xca, 0x6b, 0xa3,
	0x50, 0x7e, 0x18, 0x23, 0x5b, 0x03, 0x1f, 0xf6, 0x53, 0x4e, 0xc9, 0xe7, 0x06, 0x5c, 0xbc, 0xcf,
	0x9b, 0x82, 0xb7, 0x5c, 0xde, 0x4e, 0x91, 0xc9, 0x3d, 0x7f, 0x32, 0xc3, 0xfc, 0x9a, 0x3f, 0x1b,
	0x30, 0xbf, 0x2b, 0x45, 0x40, 0xdb, 0x6c, 0x5d, 0x6e, 0xf2, 0x28, 0x9c, 0xe3, 0x2e, 0x13, 0xb2,
	0x0d, 0xb9, 0xbb, 0xac, 0x8f, 0x69, 0xf0, 0x0e, 0x82, 0xad, 0x9e, 0x7a, 0x0c, 0xcf, 0x13, 0xbc,
	0xd6, 0x74, 0x39, 0x0d, 0xfa, 0xd6, 0x6d, 0xd6, 0x6b, 0xf4, 0x25, 0x0b, 0xed, 0x08, 0xc9, 0xfc,
	0xc5, 0x80, 0x12, 0x92, 0xc6, 0x14, 0x40, 0x17, 0xc6, 0xb8, 0x5c, 0x90, 0x5d, 0x98, 0x56, 0x61,
	0x1f, 0x0f, 0x6b, 0x8d, 0x65, 0xbe, 0x0c, 0xa0, 0xb2, 0x52, 0xc7, 0xf9, 0x45, 0x98, 0x39, 0x4a,
	0x67, 0x2c, 0x4a, 0xe6, 0x26, 0xa6, 0x73, 0xa8, 0xb7, 0x2d, 0x42, 0xde, 0x73, 0x79, 0x26, 0xb7,
	0x13, 0x85, 0x5a, 0xa5, 0x3d, 0x5c, 0x9d, 0xc4, 0xd5, 0x58, 0x61, 0xfe, 0x64, 0x20, 0x16, 0x86,
	0x69, 0x1f, 0xf2, 0x4a, 0x7c, 0x9f, 0x49, 0x5a, 0x36, 0x96, 0x72, 0xcb, 0xc5, 0xc6, 0x1b, 0x78,
	0xb2, 0xd7, 0x52, 0x27, 0x93, 0x8c, 0xb7, 0x58, 0xe0, 0xb9, 0x5c, 0x66, 0xfe, 0xf6, 0x7d, 0x16,
	0x5a, 0x03, 0x7b, 0x3b, 0x81, 0x22, 0x77, 0x60, 0x5a, 0x09, 0xaa, 0xa6, 0x8a, 0x8d, 0x6b, 0x88,
	0x79, 0xe5, 0x2c, 0x98, 0xb6, 0x86, 0x30, 0xbf, 0x31, 0xa0, 0xa8, 0xcf, 0x8f, 0xa4, 0xab, 0x00,
	0xf7, 0x68, 0x28, 0x53, 0x11, 0x98, 0xb6, 0x53, 0x1a, 0x12, 0xa4, 0x0f, 0x75, 0x7a, 0x51, 0x8f,
	0xe3, 0xc0, 0xe6, 0x5f, 0x39, 0x28, 0xee, 0x4a, 0x2a, 0xbb, 0x31, 0xc9, 0x0f, 0x60, 0x6e, 0x4b,
	0xb4, 0xd8, 0x26, 0x3f, 0x14, 0xcf, 0xa8, 0x9a, 0xe1, 0x7e, 0xfc, 0xba, 0x6f, 0xc5, 0xc6, 0xf6,
	0x00, 0x86, 0x1c, 0x40, 0x61, 0x83, 0x71, 0x16, 0xba, 0xe1, 0x6d, 0x1a, 0x1e, 0x8d, 0x27, 0x11,
	0xd3, 0x88, 0x64, 0x1b, 0x66, 0x76, 0xba, 0xcd, 0xa8, 0x6e, 0x72, 0x0a, 0x7b, 0x0d, 0xb1, 0x6b,
	0xa3, 0xd5, 0xf9, 0x4e, 0xb7, 0xd9, 0x71, 0x9d, 0xbb, 0xac, 0x6f, 0x23, 0x0c, 0x69, 0xc3, 0xb9,
	0x7b, 0x54, 0xb2, 0x50, 0xea, 0xde, 0x1b, 0xb1, 0x9e, 0x1a, 0x07, 0xeb, 0x93, 0xa8, 0xe4, 0x0a,
	0x5c, 0x48, 0xab, 0x74, 0x66, 0x4c, 0xab, 0xec, 0x7f, 0x7a, 0x81, 0x2c, 0x67, 0x68, 0xed, 0xb9,
	0x1e, 0x2b, 0xcf, 0x2c, 0x19, 0xcb, 0x39, 0xfb, 0xa4, 0x3a, 0xba, 0x49, 0xa2, 0xf0, 0xef, 0xb3,
	0x20, 0x74, 0x05, 0x2f, 0xcf, 0x2e, 0x19, 0xcb, 0x79, 0x3b, 0xad, 0x32, 0xbf, 0x9c, 0x84, 0xf2,
	0xcd, 0xae, 0xe7, 0xdf, 0x10, 0x3c, 0x64, 0x3c, 0xec, 0x86, 0x51, 0x16, 0xc4, 0x5d, 0xc8, 0x05,
	0xb0, 0x45, 0x97, 0xb7, 0x94, 0x0e, 0xd3, 0x60, 0x13, 0x8f, 0xbe, 0x7e, 0x6a, 0x1a, 0x38, 0x31,
	0x24, 0x26, 0x5e, 0x02, 0xb5, 0xeb, 0x7a, 0x7e, 0x87, 0xd9, 0x29, 0xf0, 0xe8, 0x1e, 0x39, 0xb7,
	0xc3, 0x58, 0x90, 0xa8, 0x46, 0xb9, 0xd0, 0x36, 0x90, 0xcc, 0xf5, 0x33, 0x93, 0xc9, 0xfa, 0xb2,
	0x4f, 0xfa, 0x36, 0x3f, 0x36, 0xa0, 0x84, 0xb9, 0x85, 0xc1, 0x08, 0x60, 0x16, 0x15, 0xaa, 0xd3,
	0x3c, 0x9b, 0xd8, 0xdb, 0x48, 0xec, 0xda, 0x28, 0x97, 0x9b, 0x1f, 0x08, 0x5f, 0x84, 0xb4, 0x63,
	0x21, 0xbe, 0x1d, 0x3b, 0x32, 0xbf, 0x37, 0xa0, 0x74, 0xe3, 0x88, 0xba, 0x7c, 0xb3, 0x85, 0x2c,
	0x16, 0x21, 0xaf, 0x14, 0x5b, 0xd4, 0xd3, 0x5f, 0x24, 0x6f, 0x27, 0x0a, 0x52, 0x86, 0x59, 0xdc,
	0xae, 0xca, 0x2b, 0x6f, 0xc7, 0xe2, 0xc9, 0xe2, 0xcb, 0x8d, 0xbb, 0xf8, 0xcc, 0x2f, 0x0c, 0x58,
	0xb8, 0xcf, 0x1d, 0xc1, 0x0f, 0xdd, 0xc0, 0x63, 0xad, 0xbd, 0x5e, 0x1c, 0xb7, 0x05, 0x98, 0xbe,
	0x31, 0x18, 0x21, 0xa7, 0x6d, 0x2d, 0x10, 0x0a, 0xb9, 0xbd, 0xde, 0x28, 0x63, 0xc2, 0x0a, 0x72,
	0x7c, 0xf5, 0x14, 0x8e, 0xb2, 0x17, 0x5a, 0xb7, 0xf8, 0x43, 0xd6, 0x11, 0x3e, 0xb3, 0x23, 0x6c,
	0xf3, 0x6a, 0x34, 0x99, 0xa4, 0x09, 0x0d, 0xae, 0x29, 0x8f, 0xf6, 0x22, 0xe7, 0x9a, 0x10, 0x4a,
	0xe6, 0xa7, 0x06, 0xcc, 0xeb, 0xca, 0xf9, 0xff, 0xa9, 0xff, 0x60, 0x40, 0x69, 0x8b, 0xc9, 0xa8,
	0x6d, 0x26, 0xdf, 0x3d, 0x02, 0x66, 0xdc, 0xe5, 0x6d, 0x45, 0x67, 0xce, 0x4e, 0x14, 0xc9, 0x2a,
	0xc3, 0x39, 0x30, 0x6f, 0x27, 0x0a, 0x72, 0x00, 0x53, 0x51, 0x7a, 0x8f, 0xc0, 0xb8, 0x86, 0x8c,
	0x5f, 0x19, 0x61, 0xbe, 0x57, 0x15, 0xa3, 0x80, 0x4d, 0x0e, 0x85, 0xe8, 0x37, 0x0e, 0x5b, 0xec,
	0xcf, 0x78, 0x5e, 0xfe, 0x02, 0x28, 0xed, 0x05, 0x94, 0x87, 0xd4, 0x91, 0xbe, 0x7a, 0xa8, 0x50,
	0xc8, 0xc9, 0xde, 0x28, 0x75, 0xf9, 0xef, 0x3e, 0x89, 0xec, 0x85, 0xe6, 0x87, 0x30, 0x6b, 0x33,
	0x87, 0xb9, 0xbe, 0x24, 0x87, 0x30, 0xb3, 0xd7, 0x53, 0x65, 0x74, 0xba, 0xc3, 0x3a, 0x3a, 0xbc,
	0x3c, 0x82, 0x43, 0xc4, 0xb7, 0x11, 0xbd, 0xfe, 0xed, 0x64, 0xf2, 0xf2, 0x21, 0xab, 0x00, 0x1b,
	0x4c, 0xa2, 0x48, 0x88, 0x15, 0xbd, 0x42, 0xad, 0xf4, 0x73, 0xb0, 0x72, 0x11, 0x75, 0x99, 0x67,
	0xcb, 0x5a, 0x54, 0xf7, 0x72, 0x80, 0x42, 0x32, 0x7b, 0xb4, 0xdd, 0x42, 0x46, 0x17, 0x7f, 0xc4,
	0x95, 0xa8, 0xff, 0xc9, 0xd4, 0xa4, 0x5f, 0xd0, 0xdb, 0xd4, 0x53, 0xb4, 0xf2, 0x82, 0x16, 0x4e,
	0xbe, 0x5c, 0xd6, 0x14, 0x49, 0x1c, 0x65, 0x09, 0x02, 0x67, 0xc7, 0xf1, 0x98, 0x66, 0x76, 0xde,
	0x7d, 0x13, 0x8a, 0x89, 0xe1, 0xba, 0x3c, 0x83, 0x69, 0xfd, 0xc7, 0x1c, 0x4e, 0xa1, 0xaa, 0xd5,
	0x91, 0x1a, 0xcc, 0x6d, 0x30, 0x7d, 0x05, 0x92, 0xf3, 0x7a, 0x7f, 0x32, 0xa3, 0x56, 0x2e, 0xa4,
	0x34, 0xe8, 0xba, 0x0e, 0xf9, 0xd8, 0x20, 0x24, 0xe9, 0x75, 0xdd, 0x2f, 0x2a, 0x24, 0xad, 0x42,
	0x9b, 0x2b, 0xca, 0x26, 0x54, 0x03, 0x53, 0x36, 0x30, 0x24, 0xa6, 0x98, 0x9a, 0xa5, 0x56, 0x61,
	0x7e, 0x83, 0xc9, 0xd4, 0xdd, 0x3c, 0x1a, 0xb1, 0x77, 0xe1, 0xc2, 0x06, 0x93, 0xd9, 0x8b, 0x39,
	0xeb, 0xac, 0xaa, 0x85, 0x7f, 0xbc, 0xbf, 0x2d, 0xf5, 0x39, 0xb0, 0x4b, 0x67, 0x4d, 0x31, 0x94,
	0xd9, 0x2b, 0x4e, 0xef, 0xd7, 0x57, 0xc6, 0xcd, 0xa1, 0xfb, 0xb3, 0x97, 0xd1, 0xaa, 0x4a, 0xae,
	0xb8, 0x69, 0x0e, 0x39, 0xd5, 0x42, 0x4a, 0x33, 0x68, 0xab, 0xf5, 0xcf, 0x0c, 0x28, 0xc4, 0xf5,
	0xeb, 0x0a, 0x4e, 0x5e, 0x87, 0x42, 0x23, 0x10, 0xb4, 0xe5, 0xd0, 0x50, 0xee, 0xf5, 0x08, 0xba,
	0xca, 0x54, 0x78, 0xa5, 0xa4, 0x95, 0x71, 0x09, 0xde, 0x51, 0xb1, 0xc9, 0xb6, 0x77, 0xf2, 0x92,
	0xde, 0x33, 0xa4, 0xe9, 0x57, 0x2a, 0xc3, 0x96, 0x90, 0x8e, 0x0b, 0xb3, 0x5b, 0x4c, 0x7e, 0x24,
	0x82, 0x07, 0xa4, 0xae, 0xbe, 0x14, 0x4a, 0x6a, 0x68, 0x1d, 0x16, 0x84, 0x6c, 0x67, 0xbe, 0xac,
	0x12, 0x4e, 0xf5, 0xbf, 0xec, 0x6e, 0xfc, 0xa4, 0xa9, 0xce, 0xd8, 0x58, 0x7c, 0xf4, 0xa4, 0x3a,
	0xf1, 0xfb, 0x93, 0xea, 0xc4, 0x9f, 0x4f, 0xaa, 0x13, 0x5f, 0x1d, 0x57, 0x27, 0xbe, 0x3e, 0xae,
	0x4e, 0xfc, 0x7a, 0x5c, 0x35, 0x1e, 0x1d, 0x57, 0x8d, 0xe6, 0x8c, 0xea, 0x1f, 0x2b, 0x7f, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x14, 0x8a, 0xfb, 0xa1, 0x7e, 0x12, 0x00, 0x00,
}
